version: "3.8"

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
      - adminer
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html
    networks:
      inception:
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - WP_URL
      - WP_TITLE
      - WP_ADMIN
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL
      - WP_EDITOR_USER
      - WP_EDITOR_PASS
      - WP_EDITOR_EMAIL

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      inception:
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD

  adminer:
    build: requirements/bonus/adminer/
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      inception:

volumes:
  wp-volume:
    name: wp-volume
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/web
      o: bind
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

networks:
  inception:
    driver: bridge