-- MYSQL_DATABASE=wordpressDB
-- MYSQL_ROOT_PASSWORD=rootpass
-- MYSQL_USER=shmorish
-- MYSQL_PASSWORD=pass

CREATE DATABASE ${DB_NAME};
CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
