name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          docker compose -f srcs/docker-compose.yml build
          docker compose -f srcs/docker-compose.yml up -d
          docker ps -a
